# https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        files: \.(js|tsx|ts|jsx|scss)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.28.0
    hooks:
      - id: eslint
        args:
          # https://eslint.org/docs/user-guide/command-line-interface#-fix
          - "--fix"
          # https://eslint.org/docs/user-guide/command-line-interface#-max-warnings
          - "--max-warnings"
          - "0"
        additional_dependencies:
          # should match the eslint dependencies in package.json
          - "eslint@7.28.0"
          - "@typescript-eslint/eslint-plugin@4.9.0"
          - "@typescript-eslint/parser@4.20.0"
          - "eslint-plugin-security@1.4.0"
          - "eslint-plugin-react@7.24.0"
          - "eslint-plugin-react-hooks@4.2.0"
          - "eslint-plugin-react-redux@3.3.2"
        files: \.[jt]sx?$
        types: [file]
