apiVersion: v1
kind: extensionPoint
metadata:
  id: com.apartments.property.button
  version: 0.0.1
  name: Apartments.com Button
  description: Add a Button to Apartments.com
  author: pixiebrix
definition:
  type: menuItem
  reader:
    - com.apartments.property.reader
    - document: pixiebrix/context-reader
  isAvailable:
    matchPatterns: https://www.apartments.com/*
    selectors: "#propertyHeader"
  containerSelector:
    - "#propertyHeader"
    - ".propertyInformationColumn"
  template: |
    <div class="favoriteBox">
      <a href="#" onClick="javascript:void(0);" title="{{caption}}">{{&icon}}</a>
    </div>
