apiVersion: v1
kind: extensionPoint
metadata:
  id: com.linkedin.organization.button
  version: 0.0.1
  name: LinkedIn Company Button
  description: Add a button to the LinkedIn company page
  author: pixiebrix
definition:
  type: menuItem
  reader: com.linkedin.organization.summary
  isAvailable:
    matchPatterns: https://*.linkedin.com/company/*
    selectors: ".organization-outlet"
  defaultOptions:
    caption: Custom Action
  containerSelector:
    - ".org-top-card-primary-actions"
  template: |
    <button class="org-top-card-primary-actions__action-inner artdeco-button artdeco-button--secondary">
        {{caption}}
    </button>
