apiVersion: v1
kind: extensionPoint
metadata:
  id: com.linkedin.person.contactInfo.button
  version: 0.0.1
  name: LinkedIn Contact Info Button
  description: Add a button to the LinkedIn Contact Info dialog
  author: pixiebrix
definition:
  type: menuItem
  reader:
    - com.linkedin.person.summary
    - com.linkedin.person.contactInfo
  isAvailable:
    matchPatterns: https://*.linkedin.com/*/detail/contact-info/
    selectors: "#profile-content"
  defaultOptions:
    caption: "Custom Action"
  containerSelector:
    - ".pv-contact-info"
  template: |
    <button class="artdeco-button artdeco-button--secondary">
      {{caption}}
    </button>
