apiVersion: v1
kind: extensionPoint
metadata:
  id: pixiebrix/examples-trello-card-action
  version: 0.0.1
  name: Trello card action
  description: Add a suggestion action to Trello cards
  author: pixiebrix
definition:
  type: menuItem
  reader: pixiebrix/examples-trello-card-reader
  isAvailable:
    matchPatterns: https://trello.com/*
  containerSelector:
    - ".card-detail-window"
    - ".window-module.suggested-actions-module"
    - ".u-clearfix"
  template: |
    <a class="button-link" href="#" title="{{caption}}">
      <span class="icon-sm icon-member"></span>
      <span class="js-sidebar-action-text">{{caption}}</span>
    </a>
